// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZX-AstVHiepTUwMOMNEH7OCWkTDtypQ',
    appId: '1:512294120879:android:4024afe6df5d7a6886935a',
    messagingSenderId: '512294120879',
    projectId: 'gigoe-detection-c2466',
    databaseURL: 'https://gigoe-detection-c2466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gigoe-detection-c2466.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Hs1vNrzYiAhWoQN1Ap2DD5dXUcge2NE',
    appId: '1:512294120879:ios:da53a43368cd2f4d86935a',
    messagingSenderId: '512294120879',
    projectId: 'gigoe-detection-c2466',
    databaseURL: 'https://gigoe-detection-c2466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gigoe-detection-c2466.firebasestorage.app',
    iosBundleId: 'com.example.gigoeDetectionApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Hs1vNrzYiAhWoQN1Ap2DD5dXUcge2NE',
    appId: '1:512294120879:ios:819dcb56cd52dee886935a',
    messagingSenderId: '512294120879',
    projectId: 'gigoe-detection-c2466',
    databaseURL: 'https://gigoe-detection-c2466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gigoe-detection-c2466.firebasestorage.app',
    iosBundleId: 'com.example.gigoe-detection-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC0qUVH-EikN7n6VpWfWhP8K970H05uWI',
    appId: '1:512294120879:web:a858fbee7ea865dc86935a',
    messagingSenderId: '512294120879',
    projectId: 'gigoe-detection-c2466',
    authDomain: 'gigoe-detection-c2466.firebaseapp.com',
    databaseURL: 'https://gigoe-detection-c2466-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gigoe-detection-c2466.firebasestorage.app',
    measurementId: 'G-BZLXD6241K',
  );

}