name: iOS Build

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Memungkinkan Anda menekan tombol "Run workflow" secara manual di GitHub

jobs:
  build-ios:
    runs-on: macos-14 # Menggunakan server macOS 14 (M1) dengan Xcode 15+

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Latest Xcode (Wajib untuk Firebase & Swift)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Menggunakan versi Flutter stabil terbaru

      - name: Disable Swift Package Manager (Fix rsync bug)
        run: flutter config --no-enable-swift-package-manager

      - name: Install dependencies
        run: flutter pub get

      - name: Force iOS Deployment Target to 15.0
        run: |
          cd ios
          sed -i '' 's/# platform :ios, .*/platform :ios, '\''15.0'\''/g' Podfile || true
          sed -i '' 's/platform :ios, .*/platform :ios, '\''15.0'\''/g' Podfile || true

      - name: Fix rsync mkdir error for Swift Package Manager
        run: mkdir -p build/ios/SourcePackages

      - name: Build iOS (Tanpa Code Signing)
        run: flutter build ios --release --no-codesign

      - name: Create Unsigned IPA (Untuk Sideloading di Windows)
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          # Pindahkan Runner.app ke dalam folder Payload
          mv Runner.app Payload/
          # Zip folder Payload menjadi file .ipa
          zip -qr app-unsigned.ipa Payload

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-ipa
          path: build/ios/iphoneos/app-unsigned.ipa
